[package]
name = "cuzk-proto"
version = "0.1.0"
edition.workspace = true
license.workspace = true
description = "Protobuf definitions for the cuzk proving engine gRPC API"

[dependencies]
prost = { workspace = true }
prost-types = { workspace = true }
tonic = { workspace = true }

[build-dependencies]
tonic-build = "0.12"
